import vars, { spacingVars_numbers } from '../variables'

export const marginPropStyles = {
  margin0: 'margin: 0;',
  margin0i: 'margin: 0 !important;',
  margin: `margin: ${vars.$spacing};`,
  marginY: `margin-top: ${vars.$spacing}; margin-bottom: ${vars.$spacing};`,
  marginX: `margin-left: ${vars.$spacing}; margin-right: ${vars.$spacing};`,

  ma0: `margin: ${spacingVars_numbers.$spacing_0};`,
  ma0i: `margin: ${spacingVars_numbers.$spacing_0} !important;`,
  ma1: `margin: ${vars.$spacing_extra_small};`,
  ma2: `margin: ${vars.$spacing_small};`,
  ma3: `margin: ${vars.$spacing_medium};`,
  ma4: `margin: ${vars.$spacing};`,
  ma5: `margin: ${vars.$spacing_large};`,
  ma6: `margin: ${vars.$spacing_extra_large};`,
  ma7: `margin: ${vars.$spacing_extra_extra_large};`,
  ma8: `margin: ${vars.$spacing_extra_extra_extra_large};`,

  ml0: `margin-left: ${spacingVars_numbers.$spacing_0};`,
  ml0i: `margin-left: ${spacingVars_numbers.$spacing_0} !important;`,
  ml1: `margin-left: ${vars.$spacing_extra_small};`,
  ml2: `margin-left: ${vars.$spacing_small};`,
  ml3: `margin-left: ${vars.$spacing_medium};`,
  ml4: `margin-left: ${vars.$spacing};`,
  ml5: `margin-left: ${vars.$spacing_large};`,
  ml6: `margin-left: ${vars.$spacing_extra_large};`,
  ml7: `margin-left: ${vars.$spacing_extra_extra_large};`,
  ml8: `margin-left: ${vars.$spacing_extra_extra_extra_large};`,

  mr0: `margin-right: ${spacingVars_numbers.$spacing_0};`,
  mr0i: `margin-right: ${spacingVars_numbers.$spacing_0} !important;`,
  mr1: `margin-right: ${vars.$spacing_extra_small};`,
  mr2: `margin-right: ${vars.$spacing_small};`,
  mr3: `margin-right: ${vars.$spacing_medium};`,
  mr4: `margin-right: ${vars.$spacing};`,
  mr5: `margin-right: ${vars.$spacing_large};`,
  mr6: `margin-right: ${vars.$spacing_extra_large};`,
  mr7: `margin-right: ${vars.$spacing_extra_extra_large};`,
  mr8: `margin-right: ${vars.$spacing_extra_extra_extra_large};`,

  mb0: `margin-bottom: ${spacingVars_numbers.$spacing_0};`,
  mb0i: `margin-bottom: ${spacingVars_numbers.$spacing_0} !important;`,
  mb1: `margin-bottom: ${vars.$spacing_extra_small};`,
  mb2: `margin-bottom: ${vars.$spacing_small};`,
  mb3: `margin-bottom: ${vars.$spacing_medium};`,
  mb4: `margin-bottom: ${vars.$spacing};`,
  mb5: `margin-bottom: ${vars.$spacing_large};`,
  mb6: `margin-bottom: ${vars.$spacing_extra_large};`,
  mb7: `margin-bottom: ${vars.$spacing_extra_extra_large};`,
  mb8: `margin-bottom: ${vars.$spacing_extra_extra_extra_large};`,

  mt0: `margin-top: ${spacingVars_numbers.$spacing_0};`,
  mt0i: `margin-top: ${spacingVars_numbers.$spacing_0} !important;`,
  mt1: `margin-top: ${vars.$spacing_extra_small};`,
  mt2: `margin-top: ${vars.$spacing_small};`,
  mt3: `margin-top: ${vars.$spacing_medium};`,
  mt4: `margin-top: ${vars.$spacing};`,
  mt5: `margin-top: ${vars.$spacing_large};`,
  mt6: `margin-top: ${vars.$spacing_extra_large};`,
  mt7: `margin-top: ${vars.$spacing_extra_extra_large};`,
  mt8: `margin-top: ${vars.$spacing_extra_extra_extra_large};`,

  my0: `margin-top: ${spacingVars_numbers.$spacing_0}; margin-bottom: ${spacingVars_numbers.$spacing_0};`,
  my0i: `margin-top: ${spacingVars_numbers.$spacing_0} !important; margin-bottom: ${spacingVars_numbers.$spacing_0} !important;`,
  my1: `margin-top: ${vars.$spacing_extra_small}; margin-bottom: ${vars.$spacing_extra_small};`,
  my2: `margin-top: ${vars.$spacing_small}; margin-bottom: ${vars.$spacing_small};`,
  my3: `margin-top: ${vars.$spacing_medium}; margin-bottom: ${vars.$spacing_medium};`,
  my4: `margin-top: ${vars.$spacing}; margin-bottom: ${vars.$spacing};`,
  my5: `margin-top: ${vars.$spacing_large}; margin-bottom: ${vars.$spacing_large};`,
  my6: `margin-top: ${vars.$spacing_extra_large}; margin-bottom: ${vars.$spacing_extra_large};`,
  my7: `margin-top: ${vars.$spacing_extra_extra_large}; margin-bottom: ${vars.$spacing_extra_extra_large};`,
  my8: `margin-top: ${vars.$spacing_extra_extra_extra_large}; margin-bottom: ${vars.$spacing_extra_extra_extra_large};`,

  mx0: `margin-left: ${spacingVars_numbers.$spacing_0}; margin-right: ${spacingVars_numbers.$spacing_0};`,
  mx0i: `margin-left: ${spacingVars_numbers.$spacing_0} !important; margin-right: ${spacingVars_numbers.$spacing_0} !important;`,
  mx1: `margin-left: ${vars.$spacing_extra_small}; margin-right: ${vars.$spacing_extra_small};`,
  mx2: `margin-left: ${vars.$spacing_small}; margin-right: ${vars.$spacing_small};`,
  mx3: `margin-left: ${vars.$spacing_medium}; margin-right: ${vars.$spacing_medium};`,
  mx4: `margin-left: ${vars.$spacing}; margin-right: ${vars.$spacing};`,
  mx5: `margin-left: ${vars.$spacing_large}; margin-right: ${vars.$spacing_large};`,
  mx6: `margin-left: ${vars.$spacing_extra_large}; margin-right: ${vars.$spacing_extra_large};`,
  mx7: `margin-left: ${vars.$spacing_extra_extra_large}; margin-right: ${vars.$spacing_extra_extra_large};`,
  mx8: `margin-left: ${vars.$spacing_extra_extra_extra_large}; margin-right: ${vars.$spacing_extra_extra_extra_large};`
}

export const paddingPropStyles = {
  padding0: 'padding: 0;',
  padding0i: 'padding: 0 !important;',
  padding: `padding: ${vars.$spacing};`,
  paddingY: `padding-top: ${vars.$spacing}; padding-bottom: ${vars.$spacing};`,
  paddingX: `padding-left: ${vars.$spacing}; padding-right: ${vars.$spacing};`,

  pa0: `padding: ${spacingVars_numbers.$spacing_0};`,
  pa0i: `padding: ${spacingVars_numbers.$spacing_0} !important;`,
  pa1: `padding: ${vars.$spacing_extra_small};`,
  pa2: `padding: ${vars.$spacing_small};`,
  pa3: `padding: ${vars.$spacing_medium};`,
  pa4: `padding: ${vars.$spacing};`,
  pa5: `padding: ${vars.$spacing_large};`,
  pa6: `padding: ${vars.$spacing_extra_large};`,
  pa7: `padding: ${vars.$spacing_extra_extra_large};`,
  pa8: `padding: ${vars.$spacing_extra_extra_extra_large};`,

  pl0: `padding-left: ${spacingVars_numbers.$spacing_0};`,
  pl0i: `padding-left: ${spacingVars_numbers.$spacing_0} !important;`,
  pl1: `padding-left: ${vars.$spacing_extra_small};`,
  pl2: `padding-left: ${vars.$spacing_small};`,
  pl3: `padding-left: ${vars.$spacing_medium};`,
  pl4: `padding-left: ${vars.$spacing};`,
  pl5: `padding-left: ${vars.$spacing_large};`,
  pl6: `padding-left: ${vars.$spacing_extra_large};`,
  pl7: `padding-left: ${vars.$spacing_extra_extra_large};`,
  pl8: `padding-left: ${vars.$spacing_extra_extra_extra_large};`,

  pr0: `padding-right: ${spacingVars_numbers.$spacing_0};`,
  pr0i: `padding-right: ${spacingVars_numbers.$spacing_0} !important;`,
  pr1: `padding-right: ${vars.$spacing_extra_small};`,
  pr2: `padding-right: ${vars.$spacing_small};`,
  pr3: `padding-right: ${vars.$spacing_medium};`,
  pr4: `padding-right: ${vars.$spacing};`,
  pr5: `padding-right: ${vars.$spacing_large};`,
  pr6: `padding-right: ${vars.$spacing_extra_large};`,
  pr7: `padding-right: ${vars.$spacing_extra_extra_large};`,
  pr8: `padding-right: ${vars.$spacing_extra_extra_extra_large};`,

  pb0: `padding-bottom: ${spacingVars_numbers.$spacing_0};`,
  pb0i: `padding-bottom: ${spacingVars_numbers.$spacing_0} !important;`,
  pb1: `padding-bottom: ${vars.$spacing_extra_small};`,
  pb2: `padding-bottom: ${vars.$spacing_small};`,
  pb3: `padding-bottom: ${vars.$spacing_medium};`,
  pb4: `padding-bottom: ${vars.$spacing};`,
  pb5: `padding-bottom: ${vars.$spacing_large};`,
  pb6: `padding-bottom: ${vars.$spacing_extra_large};`,
  pb7: `padding-bottom: ${vars.$spacing_extra_extra_large};`,
  pb8: `padding-bottom: ${vars.$spacing_extra_extra_extra_large};`,

  pt0: `padding-top: ${spacingVars_numbers.$spacing_0};`,
  pt0i: `padding-top: ${spacingVars_numbers.$spacing_0} !important;`,
  pt1: `padding-top: ${vars.$spacing_extra_small};`,
  pt2: `padding-top: ${vars.$spacing_small};`,
  pt3: `padding-top: ${vars.$spacing_medium};`,
  pt4: `padding-top: ${vars.$spacing};`,
  pt5: `padding-top: ${vars.$spacing_large};`,
  pt6: `padding-top: ${vars.$spacing_extra_large};`,
  pt7: `padding-top: ${vars.$spacing_extra_extra_large};`,
  pt8: `padding-top: ${vars.$spacing_extra_extra_extra_large};`,

  py0: `padding-top: ${spacingVars_numbers.$spacing_0}; padding-bottom: ${spacingVars_numbers.$spacing_0};`,
  py0i: `padding-top: ${spacingVars_numbers.$spacing_0} !important; padding-bottom: ${spacingVars_numbers.$spacing_0} !important;`,
  py1: `padding-top: ${vars.$spacing_extra_small}; padding-bottom: ${vars.$spacing_extra_small};`,
  py2: `padding-top: ${vars.$spacing_small}; padding-bottom: ${vars.$spacing_small};`,
  py3: `padding-top: ${vars.$spacing_medium}; padding-bottom: ${vars.$spacing_medium};`,
  py4: `padding-top: ${vars.$spacing}; padding-bottom: ${vars.$spacing};`,
  py5: `padding-top: ${vars.$spacing_large}; padding-bottom: ${vars.$spacing_large};`,
  py6: `padding-top: ${vars.$spacing_extra_large}; padding-bottom: ${vars.$spacing_extra_large};`,
  py7: `padding-top: ${vars.$spacing_extra_extra_large}; padding-bottom: ${vars.$spacing_extra_extra_large};`,
  py8: `padding-top: ${vars.$spacing_extra_extra_extra_large}; padding-bottom: ${vars.$spacing_extra_extra_extra_large};`,

  px0: `padding-left: ${spacingVars_numbers.$spacing_0}; padding-right: ${spacingVars_numbers.$spacing_0};`,
  px0i: `padding-left: ${spacingVars_numbers.$spacing_0} !important; padding-right: ${spacingVars_numbers.$spacing_0} !important;`,
  px1: `padding-left: ${vars.$spacing_extra_small}; padding-right: ${vars.$spacing_extra_small};`,
  px2: `padding-left: ${vars.$spacing_small}; padding-right: ${vars.$spacing_small};`,
  px3: `padding-left: ${vars.$spacing_medium}; padding-right: ${vars.$spacing_medium};`,
  px4: `padding-left: ${vars.$spacing}; padding-right: ${vars.$spacing};`,
  px5: `padding-left: ${vars.$spacing_large}; padding-right: ${vars.$spacing_large};`,
  px6: `padding-left: ${vars.$spacing_extra_large}; padding-right: ${vars.$spacing_extra_large};`,
  px7: `padding-left: ${vars.$spacing_extra_extra_large}; padding-right: ${vars.$spacing_extra_extra_large};`,
  px8: `padding-left: ${vars.$spacing_extra_extra_extra_large}; padding-right: ${vars.$spacing_extra_extra_extra_large};`
}
